CREATE TABLE STATUS
(
  ID                    NCHAR(32) NOT NULL,
  ZAJELINTEGRATION_ID   NCHAR(32) NOT NULL,
  ZAJEL_STATUS          NVARCHAR2(50),
  CREATED_DATE          TIMESTAMP(6),
  CONSTRAINT PK_Status PRIMARY KEY (ID),
  CONSTRAINT FK_ZAJELINTEGRATION FOREIGN KEY (ZAJELINTEGRATION_ID)
  REFERENCES ZAJELINTEGRATION (ID)  
); 