//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Zajel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Emaratech.DatabaseLayer;
    
    
    public partial class ZajelContextUpd :  BaseContext<ZajelContextUpd>
    {
        public ZajelContextUpd()
            : base("name=ZajelContextUpd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZAJELINTEGRATION> ZAJELINTEGRATIONs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
    }
}
